### ISSUE TITLE
Unexpected critical error on Curios (6.0.1)

### ISSUE THREAD

**Issue by DarkGames616** [TheIllusiveC4/Curios#343] opened 2023-10-09 14:34 UTC
#### Versions (Be specific, do not write "latest"):
* Curios: 6.0.1
* Forge/Fabric: Forge (Version: 48.0.19)
#### Observed Behavior: 
Forge try to load the mod, but it gives a "Unexpected critical error".
Removing all the mods (except the Curios), doesn't work either.

Gives the error: *_"Curios API (curios) encounted an error during the common_setup event phase"_*
"_org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encounted_"
#### Expected Behavior: 
Expected that the mod loaded without problems.
#### Steps to Reproduce:
1. Downloading the mod in CurseForge.
2. Putting the mod in the mods folder.
3. Start the game, and while loading the screen, Forge says: "ERROR WHILE MOD LOADING", then pop-ups the error.
4. Removing all the mods on the mods folder, leaving Curios intact.
5. Error occur again.

Crash Log: [Console Log](https://hastebin.com/share/hasufeyaqa.bash)

**Comment by TheIllusiveC4** [comment] 2023-10-09 17:30
> Forge/Fabric: Forge (Version: 49.0.19)

I assume you mean 48.0.19, since 49 doesn't exist yet.

That's a strange error. Does it work if you downgrade Forge to, say, 48.0.0?

**Comment by DarkGames616** [comment] 2023-10-11 23:39
Yeah, my mistake for using "49.0.19"

Now it gives me a crash on the game, while downgrading to 48.0.0
![image](https://github.com/TheIllusiveC4/Curios/assets/147414695/c3e1e7dc-e2eb-40e8-a1ec-80622aa3d2fb)

While testing another version: (48.0.13)

It works perfectly while starting, and loads the menu.
Starting a new world to test it, doesn't work perfectly, doesn't appear the bar to put the accessory.

Now using the new version (that i didn't donwloaded lol.) [Version 48.0.23]
Same error.

I think the new version doesn't even start the game, so it doesn't work, but the older versions of 1.20.2 works good to start, but doesn't work while i use the mod to put the accessory.

![image](https://github.com/TheIllusiveC4/Curios/assets/147414695/977df3bc-ec29-4139-83e8-cb4ba32a81a8)
![image](https://github.com/TheIllusiveC4/Curios/assets/147414695/0b2fb351-578c-4085-8ba7-b73928cfd39c)

**Comment by TheIllusiveC4** [comment] 2023-10-15 23:50
After digging into this a bit, it seems like the latest version that will work without crashing is Forge 48.0.17. This could be a Forge issue, but I'm uncertain at this time.

For the time being, try using Forge 48.0.17 or below. If it works but you do not see any slots, be sure to add slots from either a datapack or other mods in order to have slots to access.

**Comment by mcdodge34** [comment] 2023-10-17 16:07
I have the same issue with this using latest version of forge (48.0.30), downgrading to 48.0.17 did fix the problem, I stay subscribed to see if this will be fixed.

**Comment by DarkGames616** [comment] 2023-10-17 21:48
> After digging into this a bit, it seems like the latest version that will work without crashing is Forge 48.0.17. This could be a Forge issue, but I'm uncertain at this time.
> 
> For the time being, try using Forge 48.0.17 or below. If it works but you do not see any slots, be sure to add slots from either a datapack or other mods in order to have slots to access.

Alright, at least a forge issue, and not mods fault.

Thanks.

**Comment by DBotThePony** [comment] 2023-10-18 02:13
This was fixed on Forge's side (bug in securejarhandler), but currently changes are not pushed to public because they need some polishing. Have patience.

**Comment by KapsiF** [comment] 2023-10-23 15:51
Same problem in 1.20.1 - Forge 47.2.1

**Comment by TheIllusiveC4** [comment] 2023-10-23 22:17
@KonstaVilkman I cannot reproduce this on Forge 47.2.1. Please share the crash log.

**Comment by KapsiF** [comment] 2023-10-24 13:26
@TheIllusiveC4 https://paste.ee/p/lA6je

**Comment by TheIllusiveC4** [comment] 2023-10-26 03:08
> https://paste.ee/p/lA6je

That's an issue with the Tiered mod and is unrelated to this issue.

**Comment by TheIllusiveC4** [comment] 2023-10-26 03:09
It looks like Forge 48.0.32 and above have fixed this issue, and I've just released a new Curios version to match so updating both Forge and Curios should resolve this.

**Closed as completed by TheIllusiveC4** 2023-10-26 03:09 UTC
Labels: type: bug

**Comment by Morabert** [comment] 2024-04-01 08:34
Hey, Good to Hear this is fixed in Forge 48,
Just One Problem,
There _IS No_ Forge 48 for 1.20.1
![MultiMC_Str7tvBJdp](https://github.com/TheIllusiveC4/Curios/assets/36409264/c6462512-f7aa-48a8-a184-65fa7ce2d083)

**Comment by TheIllusiveC4** [comment] 2024-04-01 08:54
That's because this issue was about a bug that occurred in 1.20.2, where the Forge version is 48.x.x.

**Comment by Morabert** [comment] 2024-04-01 10:44
I'm having the same crash in 1.20.1, however

**Comment by TheIllusiveC4** [comment] 2024-04-01 10:52
Please open up a new issue report with the bug template filled out and the crash report.
