### ISSUE TITLE
Forge 31.1.10+ does not correctly check version compatibility.

### ISSUE THREAD

**Issue by LLIaMMaH** [TheIllusiveC4/Curios#129] opened 2021-04-25 13:08 UTC
Ядро MohistMC использует последнюю версию Forge, указать какую версию использовать возможности нет. Как можно избавиться от данной ошибки?
The MohistMC kernel uses the latest version of Forge, there is no way to specify which version to use. How can you get rid of this error?

* Curios 4.0.5.1:
* Forge 31.1.13:

`-- MOD tetra --
Details:
	Mod File: SC-tetra-1.16.5-3.8.0.jar
	Failure message: Mod tetra only supports curios 4 or above
		Currently, curios is 1.16.5-4.0.5.1
	Mod Version: 3.8.0
	Mod Issue URL: https://github.com/mickelus/tetra/issues/new
	Exception message: MISSING EXCEPTION MESSAGE`

**Comment by TheIllusiveC4** [comment] 2021-04-25 16:18
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/128

Unfortunately since you in particular cannot downgrade Forge, then the only option for you is to wait until the Tetra author updates their version dependency syntax.

**Closed as completed by TheIllusiveC4** 2021-04-25 16:18 UTC
Labels: type: bug
