### ISSUE TITLE
Game crashes when opening up the menu of curios

### ISSUE THREAD

**Issue by AlpherOut** [TheIllusiveC4/Curios#3] opened 2019-03-18 18:17 UTC
The Game crashed instantly when starting the game now it crashes when you open the menu of curios in your inventory.

**Comment by TheIllusiveC4** [comment] 2019-03-18 21:30
Like I said before, please include more information in your bug reports. At the very least, I would like the Curios version, Forge version, and the crash log. Without that information, I'll have trouble resolving this.

I cannot reproduce this crash. Using Forge 25.0.88, I load up into the game and open the Curios menu just fine.

**Comment by AlpherOut** [comment] 2019-03-19 17:31
Ok, here i will hand you the information:
-the newest 1.13.2 Curios Version
-Forge 1.13.2
-there is not a crash log it just stops the game and says that the game crashed,

That's all i can hand you.

**Comment by TheIllusiveC4** [comment] 2019-03-19 18:34
Another tip is to provide exact version numbers when making bug reports, not just the Minecraft version. Forge's latest version is 25.0.88 and I have no idea if you're using that or something older so you'll have to be specific. Same for the mod version. This is especially important since Forge 1.13.2 is in beta right now and every version could have important updates/changes.

There is almost certainly a crash log of some sort. Look in your Minecraft's root folder and look through the crash-reports folder. If there really isn't anything there, you could also look through your logs in the logs folder for the end of the last session. The crash is very likely recorded somewhere. This is honestly the most important part, without a recording of what crashed I can't even make a guess at the problem since I can't reproduce it myself.

**Comment by TheIllusiveC4** [comment] 2019-04-06 03:21
@AlpherOut Can you provide the information that I requested above?

**Comment by Dragnier** [comment] 2019-04-14 05:33
I found that clicking the Curios button in the inventory with Cosmetic Armor Reworked loaded will cause a crash. Maybe they have that mod as well?

Curios: 0.10
Forge: 25.0.141
MC: 1.13.2

Crashlog: https://gist.github.com/Dragnier/1082e2ef2672199a79097a5d7103c27a

**Comment by TheIllusiveC4** [comment] 2019-04-14 06:37
@Dragnier Unfortunately, I can't reproduce that either. I've loaded up Forge 25.0.141 and Cosmetic Armor Reworked, Silent's Gear (with Silent Lib), and Curios and everything works perfectly. I can click all of the buttons as normal and they function as expected.

I appreciate the inclusion of the crash log, but in this particular instance it only makes things more confusing.  It says that the network registration is locked, but I don't know why that would happen as I clearly initialize the network well before it locks. There's something going on there, but I haven't the faintest clue and my inability to reproduce this myself makes it even more difficult to solve.

**Comment by Dragnier** [comment] 2019-04-14 11:31
My steps:

1. Load a world.
2. Immediately after joining open inventory.
3. Press Curios button in the top left.

Given that I never tried each set more than once, it could be a random error linked to timing. I'll check again later today. Might actually not matter what mods are loaded and only happen with curios if the button is pressed to quickly after world join.

**Comment by Dragnier** [comment] 2019-04-14 13:34
So, I tried again and did not get a crash with a new world. However, after closing minecraft and re-opening the same world to repeat the steps above, the curios menu is empty despite the various curios mods being loaded. Basically, I think it relates to timing somehow because I did the steps above as quickly as possible.

![Curios Bug](https://user-images.githubusercontent.com/19270499/56093560-4ceab180-5e98-11e9-8dc2-b18f48df72fe.PNG)

**Comment by TheIllusiveC4** [comment] 2019-04-14 19:07
> However, after closing minecraft and re-opening the same world to repeat the steps above, the curios menu is empty despite the various curios mods being loaded

Was it not empty before you closed Minecraft in this step?

At any point, were there any error logs popping up in the console?

My best guess here, based on your description, is that some initializations are skipped for some reason only sometimes. The initial crash problem would occur if the network registration was skipped and your current problem with the Curios menu being empty sometimes would occur if the capability registration was skipped. I see that you're using the Twitch launcher, but can you replicate this with the regular Minecraft launcher? The latter is what I've been using and I've had no problems, so there's the possibility that it may be a Twitch issue with using the current Forge 1.13.2 betas.

**Comment by Dragnier** [comment] 2019-04-14 19:38
It was not empty the first time.
There were no errors that I saw.
I'll check on a straight forge install without Twitch and let you know.

**Comment by Dragnier** [comment] 2019-04-14 22:12
It seems that it may be a Twitch App issue. I just tried about 10 times to reproduce with a straight forge install and none of these issues occurred. If you watch when you hit play inside of Twitch, it says applying patch 1 of 5 through 5 of 5 before it starts the Minecraft launcher. This may be where things are getting messed up as it is the only difference between the installs. I wonder if Forge is even aware they are doing any kind of patching pre-launcher or if Twitch even realizes it could cause problems...

**Comment by TheIllusiveC4** [comment] 2019-04-14 22:29
I have no idea, a lot of the back-end stuff involving launchers is a complete mystery to me. We can only hope that it will be resolved eventually somehow.

I'll be closing this issue for now as the OP has failed to follow up on the original issue and your similar issue seems to be most likely caused by the Twitch launcher in some capacity.

**Closed by TheIllusiveC4** 2019-04-14 22:29 UTC
Labels: cannot reproduce
