### ISSUE TITLE
New config options

### ISSUE THREAD

**Issue by MiniRaptor** [TheIllusiveC4/Curios#257] opened 2022-08-13 16:00 UTC
"Please describe the new feature or change.": Please make ability to configure equipment dropping out inventory after death. 

"Please describe why you want this feature.": For someone like me it would be much easier to play, if accessory's won't drop after death, but other loot will drop. I think it would not be very difficult to implement. But the comfort from such a function would increase significantly.

**Comment by TheIllusiveC4** [comment] 2023-09-01 05:15
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/181

**Closed as not planned by TheIllusiveC4** 2023-09-01 05:15 UTC
Labels: type: enhancement
