### ISSUE TITLE
[1.14.4] Unable to click curios in to their slots.

### ISSUE THREAD

**Issue by ProsperCraft** [TheIllusiveC4/Curios#8] opened 2019-07-24 16:34 UTC
This used to work on 1.14.3 but quit working when I moved the 1.14.3 mod to 1.14.4 and had hoped the update would fix it, but the 1.14.4. version does it as well.

#### Versions (Be specific, do not write "latest"):
* Curios: curios-FORGE-1.14.4-0.18
* Forge:1.14.4 - 28.0.13

#### Steps to Reproduce:
1. Start a new world with Mine and Slash
2. scroll mouse wheel to the equipable items
3. right click to put them in their slots.
...

Video Gif-
https://gyazo.com/4fbc11bec3daf20993bb6a96843f58df

**Comment by TheIllusiveC4** [comment] 2019-07-26 05:08
This is because Forge no longer fires the `PlayerInteractEvent.RightClickItem` event server-side in 1.14.4, leaving the Curios handler nothing to hook into. We'll have to wait for that issue to be addressed in Forge before this can be fixed, which will likely not require any effort on my part if it's a simple regression.

**Comment by TheIllusiveC4** [comment] 2019-08-03 14:39
This is fixed as of Forge 1.14.4-28.0.34.

**Closed by TheIllusiveC4** 2019-08-03 14:39 UTC
Labels: 3rd party issue, bug
