### ISSUE TITLE
1.17.1 Forge : players cannot access LAN game while having an item in a Curios slot

### ISSUE THREAD

**Issue by itkminer** [TheIllusiveC4/Curios#193] opened 2021-12-14 05:33 UTC
This bug was originally posted as an issue of Sophisticated Backpacks, it turns out to be a more widespread problem. I have for example also reproduced it with „Statues“ - I guess other mods will experience similar behavior.

Describe the bug
We're using a single player world as a private family "server" at home via OPEN to LAN option. Sophisticated Backpacks (or Statues) seem to work just fine on its own even with the Curios mod running, but once there is interaction between Curios and Sophisticated Backpacks (or Statues) it gets complicated. The single player world works fine and the owner can use Sophisticated Backpacks (or Statues) with Curios as intended. The Curios slot works. However for all other members that join via LAN the following problem arises :
Once a backpack is in the Curios Back Slot (or a statue is in the statue slot) the player can never again connect to the world while the two mods are running (actually the owner can see the player connect only to get kicked out immediately) - there are different error messages, the most common one is "java.net.socketexception : connection reset". The only way to get the player back into the world is to load the world without Curios (which means losing all equipped backpacks and their contents of course).

By the way, as long as the backpacks/statues are in the inventory of the players and not in the curios slot the game seems to work as intended, everyone can log out and back in without issues.

Info on what other mods you're using that may cause a conflict here if applicable : 

This happens in a fresh test world where the only mods running are Sophisticated Backpacks and Curios. Also reproduced with only running Curios and Statues.

To Reproduce

1.  Open a single player world to LAN with Curios and Sophisticated Backpacks (or Statues) installed. It will work just fine for the owner, you need to join with a second player to see the bug.
2.  Join the world with a second character, create a backpack and equip it to his back slot from Curios.
3. Leave the world. Don't log out your first player, keep the world running.
4. Try to reenter the world.

Expected behavior

Well, you should be able to log back in with a backback in your Curios back slot ....

Versions
Mod version that you're using. Version of forge may also be helpful in some cases

Playing on Forge 37.1.1 (also tested on 37.1.0) with Sophisticated Backpacks 3.12.1.418 and Curios 5.0.2.2 (or .3 or .4, same thing happens for all three versions).

**Comment by TheIllusiveC4** [comment] 2021-12-14 06:43
Hm, if you downgrade Curios to 5.0.1.0 for 1.17.1, does this issue still happen?

**Comment by itkminer** [comment] 2021-12-14 08:00
At least for Sophisticated Backpacks the slot simply doesn‘t work at all prior to 5.0.2.2 I think. But I never checked in an isolated test world.
Edit : OK, the concerned mods (sophisticated backpacks, statues) work fine on Curios 5.0.1 in a isolated single player test world. Unfortunately I won't be able to test the LAN thing before Friday, I'll update this thread once I try it with 5.0.1.

**Comment by TheIllusiveC4** [comment] 2021-12-14 10:41
After doing some research, I believe this is actually a Forge bug since 1.17.1-37.0.64. I was able to reproduce the same error with just Chisels & Bits as well, so this is not Curios-specific and seems to only affect LAN instances (single player and dedicated servers are unaffected).

It seems that the Forge team are aware of the issue and have a pending PR here: https://github.com/MinecraftForge/MinecraftForge/pull/8181

Edit: As for a workaround, I suppose the only thing for now would be to convert your world to a dedicated server instead of LAN.

**Comment by itkminer** [comment] 2021-12-14 16:22
Thank you for digging into this - at least now I know where this is coming from. Hopefully Forge will get fixed as I don't really want to run a permanent server on my computer.

**Comment by TheIllusiveC4** [comment] 2022-02-10 04:38
It looks like Forge has merged the PR for 1.18.1. I don't know if they plan on doing the same for 1.17.1, which is when this issue originated, but I'll be closing this issue since it should be resolved going forward.

**Closed as completed by TheIllusiveC4** 2022-02-10 04:38 UTC
Labels: type: bug
