### ISSUE TITLE
[1.16.5] Curios get duplicated and unequiped after relogging

### ISSUE THREAD

**Issue by SteaSteaStea** [TheIllusiveC4/Curios#218] opened 2022-01-31 12:19 UTC
Curios 4.0.8.0
Forge 36.2.23
#### Expected Behavior: Curios stays in it's slots after relogging.
I am playing on Enigmatica6 + a few extra mods. The curios in question are from Bountiful Baubles and Artifact.
It seems to have started after increasing the number of the slots via commands.
Possibly related to #185.
The duplicate items do not disappear.

**Comment by TheIllusiveC4** [comment] 2022-01-31 21:52
Do you know which exact commands you used, how many slots you gave yourself, and which slots were involved?

**Comment by SteaSteaStea** [comment] 2022-02-01 16:51
I used the "/curios add belt _Stea 1" command. Then again with different slot types.
Here's a screenshot after entering the world:
![2022-02-01_17 39 19](https://user-images.githubusercontent.com/76264934/152011344-ba368661-e894-44cb-b060-cee366539014.png)
The slots are belt, hands, necklace, head.
Currently I've got: 4 head slots, 4 necklace slots, 4 hands slots, 4 belt slots. 
I've got 4 charms slots occupied which seem to work fine but the other ones I've mentioned seem to unequip and duplicate on world enter.
Am I overloading it with too many slots? I'd imagine that something would break If I just started adding 20+ slots but I only added a few. Am I going over the limit?

**Comment by TheIllusiveC4** [comment] 2022-02-15 09:06
Unfortunately, I'm unable to reproduce this in my testing. Adding 3 slots to rings, totaling 4 ring slots, with the `add` command does not result in any of them being unequipped upon exiting and re-entering the world.

Does this occur on multiplayer, single-player, or both?

Are you able to reproduce this with only Curios and Bountiful Baubles _or_ Artifacts? If so, can you specify the slot type and the items involved? This could be a specific problem with an item provided by those mods.

**Comment by tillasiren** [comment] 2022-02-16 15:17
We are noticing a similar issue on our 1.18 game as well (not server owner but close contact with them). For some reason our fourth ring slot (the only slots we have added are two extra rings) keeps getting unequipped and dropped/moved to inventory on login.

**Comment by SteaSteaStea** [comment] 2022-02-17 18:10
For me it occurs on 1.16.5 singleplayer.
I tried reproducing with Artifacts, Bountiful Baubles+ curios api. After adding slots to head, feet, hands, necklace and filling up all the slots with items it ended up unequiping items from the last hand slot in order (any item in that last slot).
![image](https://user-images.githubusercontent.com/76264934/154544122-0d5122b8-710f-49b8-8ed3-f7363ba175c9.png)


When I added an extra hand slot at this point - added in the bauble that kept getting unequipped and reopened the world - it stayed in place. That means that currently there's a workaround which works by adding one extra slot which will remain unused.

![image](https://user-images.githubusercontent.com/76264934/154544216-af72dc96-5b70-463c-8831-fbf8c2065efb.png)

The duplication is probably an interaction with some other mod as it did not happen with just the 3 mods installed or maybe it is just a completely different issue unrelated to curios. With just the 3 mods installed it only ended up being unequiped.

**Comment by Aizistral** [comment] 2022-02-18 08:39
I am encountering what appears to be exactly the same issue, but with no duplication involved. As of [Enigmatic Legacy 2.16.0](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy/files) I have added an item called Celestial Fruit, which allows to permanently increase the amout of ring slots player has by one, and achieves so by adding permanent modifier (you can see the details of my implementation [here](https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/1.18.X/src/main/java/com/integral/enigmaticlegacy/items/AstralFruit.java#L69) and [here](https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/aa2d52f62fa790679cafb8df75b9f3e5f8b6bbb6/src/main/java/com/integral/enigmaticlegacy/handlers/SuperpositionHandler.java#L142-L160 
)). Third ring slot obtained in such a way indeed ejects anything and everything that I tried equipping into it upon re-logging into the world. Furthermore, one of the users reported [a bug](https://github.com/Aizistral-Studios/Enigmatic-Legacy/issues/278) to my issue tracker where they claim they experience same issue with extra slot they added themselves, for which they used `/curios add ring` command.

**Comment by TheIllusiveC4** [comment] 2022-02-22 10:20
From all the information everyone provided, I was successfully able to reproduce the issue and figure out a way to fix it. I'm currently still working on some other bug fixes, but the fix for this particular issue will be included in the next Curios update.

**Closed as completed** 2022-02-25 09:14 UTC
Labels: type: bug
