### ISSUE TITLE
Crash Ticking Player

### ISSUE THREAD

**Issue by starryfae** [TheIllusiveC4/Curios#187] opened 2021-12-01 23:41 UTC
#### Versions (Be specific, do not write "latest"):
* Curios:  1.16.5-4.0.6.2
* Forge/Fabric: Forge 36.2.19
#### Observed Behavior: 

Game crashes harvesting any item after creating world
#### Expected Behavior: 

Not crashing
#### Steps to Reproduce:

1. Have Industrial Foregoing and latest Curios

Crash Log: 

https://www.toptal.com/developers/hastebin/reyelabico.rb

**Comment by TheIllusiveC4** [comment] 2021-12-02 00:14
I cannot reproduce this, using Curios 1.16.5-4.0.6.2, Forge 36.2.19, and Industrial Foregoing 1.16.5-3.2.14.7-16.

I enter the game and harvest some dirt. When I pick it up, no crash occurs.

Can you be more specific about your reproduction steps?

**Comment by ProsperCraft** [comment] 2021-12-02 02:07
Our dedicated server just crashed with the same error, I the player was getting kicked over and over then the server quit responding and had to kill the process.

We only started having this when we updated today to 4.0.6.2

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)

Here is the tail of the debug log(too big for gist)
https://gist.github.com/ProsperCraft/6018570fb2c017ccc5e24194e38ecaef

Entire log- 
[debug.log](https://github.com/TheIllusiveC4/Curios/files/7638363/debug.log)

Latest log-
https://gist.github.com/ProsperCraft/e187d0ce2594cebeb56cff606dbe8190



curios-forge-1.16.5-4.0.6.2
forge-1.16.5-36.2.19

**Comment by TheIllusiveC4** [comment] 2021-12-02 02:24
As mentioned above, I can't reproduce this issue with the given information so I'll need a bit more.

What exactly happened when the crash occurred? List out detailed reproduction steps.

**Comment by ProsperCraft** [comment] 2021-12-02 02:29
I can't give steps, it was a player on the server who I don't have contact with.

**Comment by TheIllusiveC4** [comment] 2021-12-02 07:52
As of now, I still couldn't reproduce nor figure out the issue. However, I suspect it _might_ be related to a different issue that has been solved in the 4.0.6.3 update that I just pushed out. Can either of you try it and let me know if this issue persists?

**Comment by starryfae** [comment] 2021-12-03 02:33
Seems to be fixed now!



My steps before were just, make a new world with the mods i had installed, punch a mushroom or some wood, and it would crash upon attempting to pick up the item

**Comment by TheIllusiveC4** [comment] 2021-12-03 02:37
Alright, I do think it should be solved then. I'll be closing this, but anyone encountering this issue can let me know if it still persists and I'll reinvestigate.

**Closed as completed by TheIllusiveC4** 2021-12-03 02:37 UTC
Labels: type: bug

**Comment by ProsperCraft** [comment] 2021-12-03 05:00
We are also not having issues any longer.
