### ISSUE TITLE
Curios API encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by SmileyWasTaken** [TheIllusiveC4/Curios#431] opened 2024-07-21 22:33 UTC
### Minecraft Version

1.19.2

### What happened?

Upon launching minecraft i get this error
![image](https://github.com/user-attachments/assets/628016e4-3c45-48b1-a15a-d1af544d271e)

### How do you trigger this bug?

1. Load up minecraft

### Loader

Forge

### Loader Version

43.4.0

### Mod Version

curios-forge-1.19.2-5.1.6.3

### Relevant Log Outputs

https://mclo.gs/y4frogN

**Comment by TheIllusiveC4** [comment] 2024-07-22 00:00
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/344
This is an issue with the Tiered mod.

**Closed as not planned** 2024-07-22 00:01 UTC
Labels: type: bug, status: resolved
