### ISSUE TITLE
'curios:slot_type' is already a registered serializer

### ISSUE THREAD

**Issue by Shashlik1337** [TheIllusiveC4/Curios#278] opened 2023-01-21 13:38 UTC
#### Versions (Be specific, do not write "latest"):
* Curios: 4.0.8.2
* Forge/Fabric: FORGE 1.16.5 - 36.2.39
#### Observed Behavior: Game Crashes

Crash Log: Please use a paste site like [hastebin](https://pastebin.com/xkgukQtj).

**Comment by TheIllusiveC4** [comment] 2023-02-16 04:04
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/274

**Closed as not planned by TheIllusiveC4** 2023-02-16 04:04 UTC
Labels: type: bug, duplicate
