### ISSUE TITLE
Having any Curios equipped in 1.17.1 (newest patch) will cause players to be instantly kicked on joining of a multiplayer LAN world.

### ISSUE THREAD

**Issue by superbananazombie** [TheIllusiveC4/Curios#244] opened 2022-06-27 21:53 UTC
#### Versions (Be specific, do not write "latest"): 1.17.1
* Curios:
Mods: 
Curios-forge-1.17.1-5.0.2.7
Angel Ring 1.17.1-1.4.0
Artifacts, 1.17.1-3.0.2
Nameless Trinkets-1.17.1-1.4.3
* Forge/Fabric: Forge
#### Observed Behavior:
When any items from any curios mods are equip in the API on a non-host player, the player will be instantly kicked whenever they try to rejoin that world.
#### Expected Behavior:
No kicking
#### Steps to Reproduce:
1. Player 1 creates a world and opens it to LAN
2. Player 2 joins the world
3. Player 2 equips any curios
4. Player 2 leaves the world, and afterwards when trying to reconnect will be kicked instantly

Crash Log:
Doesn't generate a crash log, but has two different error messages that generate interchangeably:
"Internal Exception: io.netty.handler.codec.EncoderException:io.netty.util.IllegalReferenceCountException: refCnt: 0"
"Internal Exception: java.net.SocketException: Connection reset"

**Comment by TheIllusiveC4** [comment] 2022-06-28 11:23
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/193
This is a Forge bug in 1.17.1. I don't believe they ever patched it for that version, so your only option is to update to a more recent version like 1.18 or 1.19.

**Closed as not planned by TheIllusiveC4** 2022-06-28 11:23 UTC
Labels: type: bug
