### ISSUE TITLE
Crash due to Forge 1.16.1-32.0.67

### ISSUE THREAD

**Issue by kreezxil** [TheIllusiveC4/Curios#54] opened 2020-07-17 12:43 UTC
Issue:  1.16.1-3.0-beta3 crashes dedicated server Forge 1.16.1 build 32.0.68

Notes:
     No Such Method Error, this is probably caused by FORGE changing how mods process commands. **Note**: Bad Wither No Cookie Reloaded uses commands, it broke, we simply recompiled against the new forge, it is no longer crashing, not sure if you tried anything.

crash report: 
https://gist.github.com/4626ae990710169691cebcbb32c99f12

fml server latest: 
https://gist.github.com/0b78f5576493108db96ac6acd9c73c3c

**Comment by TheIllusiveC4** [comment] 2020-07-17 20:35
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/53

**Closed as completed by TheIllusiveC4** 2020-07-17 20:35 UTC
Labels: type: bug, duplicate
