### ISSUE TITLE
[Bug]: 1.20.1 crash during loading

### ISSUE THREAD

**Issue by TheSexyYeti** [TheIllusiveC4/Curios#452] opened 2024-10-26 04:29 UTC
### Minecraft Version

1.20.1

### What happened?

Not sure what is exactly causing it. But I keep getting a crash involving Curios.

### How do you trigger this bug?

I don't know

### Loader

Forge

### Loader Version

47.3.11

### Mod Version

5.11.0

### Relevant Log Outputs

https://pastecode.io/s/ge8e0c52

**Comment by TheIllusiveC4** [comment] 2024-11-05 05:56
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/344
This is an issue with the Tiered mod.

**Closed as not planned by TheIllusiveC4** 2024-11-05 05:56 UTC
Labels: type: bug, duplicate
