### ISSUE TITLE
Curios Menu won´t open when clicking the icon

### ISSUE THREAD

**Issue by jaz0894** [TheIllusiveC4/Curios#159] opened 2021-08-07 23:27 UTC
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.16.5-4.0.5.2
* Forge/Fabric: forge-1.16.5-36.2.0.jar
<html>
<body>

When I click on the curios Icon of curios nothing happens, I also have the mod Sofisticated Backpacks and when Curios is bugged I cannot open backpack inventory.

</body>
</html>
<html>
<body>

--

</body>
</html>
<html>
<body>

forge-1.16.5-36.2.0.jar
--

</body>
</html>
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment] 2021-08-08 01:01
What Curios mods do you have installed? Can you share a list of your mods? Also, is there an error that gets logged when you try to click the icon?

**Comment by jaz0894** [comment] 2021-08-08 03:17
List of Mods:

[Mods List.txt](https://github.com/TheIllusiveC4/Curios/files/6950145/Mods.List.txt)

This is the link to an MP4 video showing the issue: https://drive.google.com/file/d/1rORNEq4l9lUWaAI4HCAgLq4wzYMTjRNs/view?usp=sharing

and this the console after my demo on the video.
![Console](https://user-images.githubusercontent.com/73314134/128619555-98cc1dd2-68e2-4ac3-b85f-f6d18dc199b4.PNG)


Sorry about my uggly english, I speak spanish hehe

**Comment by TheIllusiveC4** [comment] 2021-08-08 03:33
Hmm, so you've shown this issue in multiplayer. Does this issue occur in single player? Also, what happens if you remove Optifine and test it?

**Comment by jaz0894** [comment] 2021-08-10 17:52
Ok, I removed optifine and tried again, but the issue persisted, this is happening to all players in the server not just me, I am trying to replicate on single player. The issue happens as soon as I move from one dimension to another (from overworld to nether) but only in multiplayer. The issue is fixed when I used /curios reset but the player loses everything and if he changes from dimension again it bugs out again. Also sometimes dying causes the bug or fixes it.

**Comment by TheIllusiveC4** [comment] 2021-08-10 18:07
Just making sure, you're not using something like Mohist with plugins installed right?

Is there an error log when you move dimensions and the issue occurs?

Also, if possible, can you replicate this in multiplayer with only Curios installed? If necessary, you can include something like Artifacts to generate some curio slots as well. I'm just trying to isolate any possible mod conflicts.

**Comment by jaz0894** [comment] 2021-08-10 19:20
I thoght the same, I was using Mohist with some pluggins, then we removed the pluggins, then we removed Mohist and used just the Forge. So no, we are not currently using Mohist.

there are no erros at all when we move between dimensions. I will try to replicate with just curios and Artifacts. Keep you posted

**Comment by astroACR** [comment] 2021-12-01 00:22
hope not to necro, but I'm having this exact same issue on a multiplayer server, and I am using mohist.

I have other mods besides Sophisticated Backpacks (sophisticatedbackpacks-1.16.5-3.12.0.407) that use Curio (curios-forge-1.16.5-4.0.5.3), such as Cosmetic Armor Reworked (CosmeticArmorReworked-1.16.5-v4), Colt's Cosmetic Armor (ColtCosmeticArmorMod-1.2.5), and Expanded Combat (expanded_combat-2.3.1-beta_0-1.16.5).

Every time you join, the Curio menu/GUI will not render, until you die and respawn.

If you need me to test anything, hmu

**Comment by astroACR** [comment] 2021-12-01 00:43
Nevermind, duplicate of #154. Removing SkinsRestorer solved it.

**Comment by cbunny787** [comment] 2021-12-05 08:58
i have same issue with aoa/Advent of Ascension mod Curios gui its not opening, it stop working idk when but i was able to use it and my friend was not but after few mins my stop working to no error in console/log

**Comment by J-Dill** [comment] 2022-03-03 03:34
@TheIllusiveC4 I am also seeing this behavior in curios-forge-1.18.2-5.0.6.3.jar with Forge v40.0.2.
I only have the curios mod installed. I initially noticed this while developing with the Curios API.

Here is a pastebin with my log: https://pastebin.com/mKKYSEHt

**Comment by TheIllusiveC4** [comment] 2022-03-03 05:33
>  I initially noticed this while developing with the Curios API.

Just making sure, are you sure that there are any slots registered when you see this behavior? To be clear, if there are no slots registered, then the Curios GUI naturally won't have anything to open.

**Comment by cbunny787** [comment] 2022-03-05 15:06
i only saw button i was able to click it but im not play with thos mods so
i cant check sorry for late reply and thx

**Comment by J-Dill** [comment] 2022-03-05 17:51
> > I initially noticed this while developing with the Curios API.
> 
> Just making sure, are you sure that there are any slots registered when you see this behavior? To be clear, if there are no slots registered, then the Curios GUI naturally won't have anything to open.

@TheIllusiveC4 You were right, my mod wasn't completely registering the Curio slot, which is what caused there to be no GUI. Thanks for the clarification!

**Comment by PAKITRON5000** [comment] 2022-08-17 01:30
> > > Inicialmente me di cuenta de esto mientras desarrollaba con la API de Curios.
> > 
> > 
> > Solo asegurándome, ¿está seguro de que hay espacios registrados cuando ve este comportamiento? Para ser claros, si no hay ranuras registradas, entonces la GUI de Curios, naturalmente, no tendrá nada que abrir.
> 
> @TheIllusiveC4Tenías razón, mi mod no estaba registrando completamente la ranura Curio, que es lo que causó que no hubiera GUI. ¡Gracias por la aclaración!

I have the same problem , how you config that? :( Can you help me? :)

**Comment by J-Dill** [comment] 2022-08-17 14:19
The issue ended up being because I had forgot to uncomment my piece of code that registers my item as a Curio, and at the same time registers a Curio slot type. To my understanding is that Curios doesn't register any slot types by itself; it relies on mods to register them as needed.

See [here](https://github.com/J-Dill/NoMoWanderer/blob/57616c366ecb6d929cce49f3f7de82634f718dbd/src/main/java/nomowanderer/Registry.java#L62) in my mod to see how I went about doing it.

**Closed as not planned** 2023-06-23 06:10 UTC
Labels: type: bug

**Comment by IINGE23** [comment] 2024-06-14 21:04
I been having the same issue... i solved it uninstalling the SkinsRestorer Plugin

**Comment by oszodiacYT** [comment] 2026-07-26 20:14
I have the same issue but I don't even have SkinsRestorer and I'm on singleplayer building a modpack

**Comment by cbunny787** [comment] 2026-08-06 08:27
> I have the same issue but I don't even have SkinsRestorer and I'm on singleplayer building a modpack

I would say just disable mods one by one to see what causing issue that's how I fixed it

I forgot mod that was causing issue because it's been 4 years and lost that profile
