### ISSUE TITLE
curios menu don't show up when clicking the icon in a server

### ISSUE THREAD

**Issue by Carabing** [TheIllusiveC4/Curios#338] opened 2023-09-25 18:23 UTC
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-5.3.1+1.20.1.jar
* Forge/Fabric: Forge - 47.1.1
#### Expected Behavior: the menus to show up

mod liste: 
(the mods that add slots are ars nouveau and sophisticated backpack)
Balm (Forge Edition)
Moonlight Lib
Waystones
AppleSkin
Bookshelf
 Botany Pots
 Botany Pots Tiers
Botany Trees
 Clumps
 Collective
 Comforts (Forge)
Corpse
Cosmetic Armor Reworked
 Double Doors
Enchantment Description
 Iron Furnaces [FORGE]
Jade
JourneyMap
 Just Enough Items (JEI)
Just Enough Resources (JEI)
 Macaw's Bridges
MmmMmmMmmMmm (Target Dummy)
 Nature's Compass
 OpenBlocks Elevator
Patchouli
 Productive Bees
 Sophisticated Backpacks
 Sophisticated Core
 Sophisticated Core
 Supplementaries
The Twilight Forest
 Torchmaster
Tree Harvester
Architectury API
Curious API
Artifacts
Biomes O' Plenty
Blue Skies
Caelus ApI
Cloth Config API
Cristel Lib
Curious Armor Stands
Explorer's Compass
GeckLib
Iron's Spells'n Spellbooks
Paragliders
PlayerAnimator
Relics
Sit
TerraBLender
Towns and Towers
When Dungeons Arise
XP Tome
YUNG's API
YUNG's Extras
Dynamic Lights
Vampirism - Become a vampire!

**Comment by TheIllusiveC4** [comment] 2023-09-26 20:21
Does this occur if you load _only_ Curios and Ars Nouveau or Sophisticated Backpacks?

Does this occur if you update to the latest version, 5.3.4?

**Comment by MrKashew** [comment] 2023-11-12 12:08
@Carabing did u find out if it's an incompatibility - Having this issue on latest Curios it's quite annoying. It actually appires at times and doesn't at times very weird

![image](https://github.com/TheIllusiveC4/Curios/assets/53996665/42513de9-4723-402e-80b1-04608cd6e52e)

**Comment by PauPV3** [comment] 2023-11-17 22:46
same problem

**Comment by TheIllusiveC4** [comment] 2023-11-27 06:32
Closing this as a duplicate of https://github.com/TheIllusiveC4/Curios/issues/347 as that thread has more relevant information as of now.

**Closed as not planned by TheIllusiveC4** 2023-11-27 06:32 UTC
Labels: type: bug
