### ISSUE TITLE
rings

### ISSUE THREAD

**Issue by krjencik** [TheIllusiveC4/Curios#213] opened 2022-01-28 13:06 UTC
Hi, i still have the same problem: i cant put any modded ring into the curios ring slots.. it looks like the ring slots are only one slots that doesnt work...

**Comment by krjencik** [comment] 2022-01-28 13:08
i have been told to contact curios

**Comment by TheIllusiveC4** [comment] 2022-01-28 21:18
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/210
If you have any update, please comment on the existing issue instead of making a new one.
In addition, I've already told you that I cannot reproduce your issue. If you have been told by someone to contact me, I will need some more context about what was said and why the problem is on Curios's end.

**Closed as completed by TheIllusiveC4** 2022-01-28 21:18 UTC

**Comment by krjencik** [comment] 2022-02-03 08:15
ok sorry i wont bother any more
