### ISSUE TITLE
[Bug]: Load on crash 1.19.2

### ISSUE THREAD

**Issue by TheSexyYeti** [TheIllusiveC4/Curios#438] opened 2024-08-21 01:53 UTC
### Minecraft Version

1.19.2

### What happened?

Curious API crashes while loading for 1.19.2. 

### How do you trigger this bug?

idk

### Loader

Forge

### Loader Version

43.4.2

### Mod Version

1.19.2-5.1.6.3

### Relevant Log Outputs

https://hastebin.com/share/iwopibedos.makefile

**Comment by TheIllusiveC4** [comment] 2024-08-21 07:12
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/344
It's an issue with the Tiered mod.

**Closed as not planned by TheIllusiveC4** 2024-08-21 07:12 UTC
Labels: type: bug, duplicate
