### ISSUE TITLE
I can´t add ring slot withe commands on server 

### ISSUE THREAD

**Issue by Destiny1231** [TheIllusiveC4/Curios#330] opened 2023-08-01 13:44 UTC
The command /curios add ring is not working on servern Error  Unknown curio slot type ring 
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-5.2.0-beta.3+1.20.1.jar
* Forge/Fabric: Forge - 47.1.3
#### Steps to Reproduce:
1. Typing command for mor ring slot´s
2. command can´t find slot type
![command not working](https://github.com/TheIllusiveC4/Curios/assets/80947705/ed148c47-5072-4e51-a34f-94383bf7ca25)

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment] 2023-08-03 08:36
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/327

**Closed as not planned by TheIllusiveC4** 2023-08-03 08:36 UTC
Labels: type: bug, duplicate
