### ISSUE TITLE
Curios API (curios) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by nikoxdios** [TheIllusiveC4/Curios#336] opened 2023-09-20 10:19 UTC
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Curios: curios-forge-5.3.2+1.20.1
Forge: Forge-47.1.47

Mods used:
 *curios-forge-5.3.2+1.20.1 (https://www.curseforge.com/minecraft/mc-mods/curios/files/4758692)
 *Tiered-1.20.1-6.0.2-Forge (https://www.curseforge.com/minecraft/mc-mods/tiered-forge/files/4752364)
 *UnionLib-1.20.1-10.2.0-Forge (https://www.curseforge.com/minecraft/mc-mods/unionlib/files/4751666)

1. Launch the game with these mods to reproduce this error.

Crash Log: https://hastebin.com/share/kotunucuhu.php

**Comment by TheIllusiveC4** [comment] 2023-09-21 00:38
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/335

**Closed as not planned by TheIllusiveC4** 2023-09-21 00:38 UTC
Labels: type: bug
