### ISSUE TITLE
Curios Inventory Not Working in Server

### ISSUE THREAD

**Issue by NieXavosao** [TheIllusiveC4/Curios#154] opened 2021-07-12 01:51 UTC
I have a modpack server
but the curios inventory isnt working (only in the server)
When i use the backpack (from backpacked) the backpack just disappear and I can't use it
but the other players can see my backpack.

####Versions:
* Curios:4.0.5.2
* Forge:36.1.32
#### Steps to Reproduce:

1. The Curios Inv button isnt working but exist

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by NieXavosao** [comment] 2021-07-12 01:59
ok i just used the command reset and worked

**Comment by NieXavosao** [comment] 2021-07-12 02:42
OK SO THE COMMAND IS HELPING, BUT EVERYTIME I OPEN THE SERVER I NEED TO USE THIS COMMAND

**Comment by TwistedPorkchop** [comment] 2021-07-14 12:32
I'm having the same issue. And If I end up using the command I'll lose any items that were slotted. So it's not a viable solution.

**Comment by Semzaiy** [comment] 2021-07-16 18:36
I have the same bug, its really annoying and i hope it will be fixed asap.
When i reset my curios inventory is gone and i want to use an elytra as back but i keep losing it.

**Comment by TwistedPorkchop** [comment] 2021-07-16 20:56
Since its a server side issue I would guess it has to do with a plugin or mod installed from either rone of us. Could both of you (@Semzaiy , @NieXavosao ) give a list of plugins and mods installed on your servers? 
Mine are : 

 abnormals.core
 alexsmobs
 appleskin-forge-mcl
 appliedenergistics
 AutoRegLib
 BloodMagic
 Botania 
 Bookshelf
 carryon
 Citadel
 CTM -MC1
 curios-forge
 forgeessentials
 gravestone
 Hwyla-forge-l
 jei
 Jei integration
 journeymap
 lootr
 OreExcavation
 pamhc2foodcore
 Patchouli
 Quark
 QuarkOddities
 reap
 sophisticatedbackpacks
 swingthroughgrass
 TooIBelt
 twilightforest
 VanillaFix
 WAWLA
 Waystones

And the Plugins:
 bStats
 ClearLag
 Clearlag .jar
 Essentials
 EssentialsGeolP
 EssentialsX
 EssentialsXAnti Build
 EssentialsXChat
 EssentialsXGeolP
 EssentialsXProtect
 EssentialsXSpawn
 SkinsRestorer

If we see any overlaping plugins/mods it might help us understand the issues. Thanks

**Comment by TheIllusiveC4** [comment] 2021-07-16 22:32
@TwistedPorkchop Wait, plugins? So this is not a strictly Forge environment then? What are you using to load the plugins?

**Comment by TwistedPorkchop** [comment] 2021-07-16 22:36
@TheIllusiveC4 
Oh yeah no the server I'm running def can't run without plugins helping out a bit. We are running using mohist do you think that's the issue?

**Comment by TheIllusiveC4** [comment] 2021-07-16 22:57
Yes that means your issue is a duplicate of https://github.com/TheIllusiveC4/Curios/issues/131
If I understand the previous issue correctly, I think you can make it work with plugins just without SkinsRestorer which seems to be the main cause of the issue.

I am curious if the others encountering the issue in this thread are also running plugins.

Edit: But anyways, the main thing is that if it is caused by a plugin issue, there's not much I can do on my end about it.

**Comment by TwistedPorkchop** [comment] 2021-07-16 23:35
@TheIllusiveC4 
I am so disgruntled. You were exactly right it was the skin restorer pluging. I'm sorry for not having seen that thread. And yeah it's definitely not your job to make your mod work with other plugins. Thanks for helping I guess we'll find another way around losing our skins. :)

**Comment by Semzaiy** [comment] 2021-07-18 14:58
Oh, time to delete the skin restorer pluging :d
Thanks for the help :)

**Closed as completed** 2021-09-11 22:31 UTC
Labels: type: bug

**Comment by Keparfo** [comment] 2023-11-08 03:58
For people who still have the problem, you should remove SkinRestorer, but you could put the [OfflineSkins](https://www.curseforge.com/minecraft/mc-mods/offlineskins) By mod
LainMI, could help you in some way, at least it solves the problem that if you are premium you can see your skin.
